### PR TITLE
Body parsers

### PR DESCRIPTION
**Pull request by Agrosis**
I was originally planning on parameterizing `Body` with `JsValue` or `Map[String, String]` but that really messed with the routing and middleware composition stuff because we want to be able to have multiple body types, and in the end, we couldn't group a bunch of controllers that had different body types together.

I still don't feel like this is the best way to do it because while each controller can specify its own body type, it still makes writing middleware a bit more confusing (you have to manually call the next controller's body parser). ideas?

### CODE REVIEW

**Comment by Agrosis** [comment]
I was playing around a little bit, and if we use an abstract class for Controller, we can use context bounds when we create a controller, so we'd be able to implicitly grab `BodyParser[JsValue]` if we extended `Controller[SimpleRequest, JsValue]`. But, this still doesn't solve the problem of reconciling all the types in all the routing constructs.

**Comment by JosephMoniz** [comment]
Hmmm this gets us close. I think we should try to keep the `Controller` interface as clean as possible though.

Perhaps this is an opportunity for leveraging the custom request type and making the population of the  body done through an opt in top level middleware.

The middleware can be something like `BodyParserMiddleware(BodyParser, (Request, Body) => Request)`. This will preserve the controller interface in regards to the method signature of `action`. It also makes body parsing an opt-in thing for the framework user.

I also think we might have to add a default pass through method to the base middleware trait so that we can grab the desired body parser from any layer in the middleware chain from the controller at the end. Something like `def getBodyParser(): BodyParser = next.getBodyParser()`

**Comment by Agrosis** [comment]
Cool, so my latest commit, we can do something like this:

```scala
case class MyController() extends Controller[SimpleHttpRequest] {
  override def middleware() = List(
    BodyParserMiddleware((request, body: JsonBody) => request)
  )

  override def action(implicit request: SimpleHttpRequest): Box[Throwable, HttpResponse] = Ok("")
}
```

`BodyParserMiddleware((request, body: JsonBody) => request)` is the important part. We can also write this like `BodyParserMiddleware[SimpleHttpRequest, JsonBody]((request, body) => request)`. Should we just not context bounds and have the user specify the `BodyParser` they want explicitly?

**Comment by JosephMoniz** [comment]
Context bounds and implicit don't seem to buy us much in this case. It would probably result in a much cleaner interface if we just have the middleware user explicitly pass in the body parser instead of leaning on implicit resolution.

**Comment by Agrosis** [comment]
```scala
case class MyController() extends Controller[SimpleHttpRequest] {
    override def middleware = List(
      BodyParserMiddleware(JsonBodyParser(), (request, body: Body) => request)
    )
    override def action(implicit request: SimpleHttpRequest): Box[Throwable, HttpResponse] = ???
  }
```

Is the usage now.

**Comment by JosephMoniz** [comment]
Looks legit.

**Pull request merged**
